### ISSUE TITLE
Silly issue: Every new account is an admin? 

### ISSUE THREAD

**Issue by Teku16** [toontownfellowship/src#130]
Please don't laugh at me, lol. I have looked in a large amount of files and the closest I found was in /config/release/dev.prc but changing that to 100(anything besides 600) does nothing. The new accounts still get assigned "ACCESS_LEVEL" to 600. Obviously this is an issue. Where do I change that?

**Comment by ToontownLittleCat** [comment]
That's maybe because the account type on the server is set to 'developer'.  You see, when a new account is made when the type is on, it always sets their access level to 600.

If you like normal accounts on your server, you can set your account type to 'local' on dev.prc
https://github.com/toontownfellowship/src/blob/master/config/release/dev.prc#L10

When it's set to local, the first account made on the database (If there isn't any and 'account-bridge.db' is deleted) It sets its access to one marked on 'min-access-level' (600 by default) and then, all the account made after that are set to 100.

Hope that helps you out.

**Comment by Teku16** [comment]
@ToontownLittleCat thank you for your reply. I made this change and a new account still got access level 600 when I set "min-access-level 600" and "accountdb-type local". Also, how do I wipe the databases cleanly and correctly?

**Comment by ToontownLittleCat** [comment]
@Teku16 On astron/databases/astrondb, Delete all the .yaml files. Also, and on databases, make sure to delete the account-bridge.db folder as well.  Oh, and when you make changes to dev.prc, make sure you restart your servers.  Changes won't affect on its own immediately.

**Comment by Teku16** [comment]
@ToontownLittleCat I was able to reset the db properly :) but each account (After the first one) are still all user access 600 :/

**Comment by ToontownLittleCat** [comment]
Huh, let me try this for myself, I'll get back to you if I got anything.

**Comment by Teku16** [comment]
@ToontownLittleCat Thanks :) Could I have edited a part of the code for the access that maybe botched the accountdb-type local command?

**Comment by ToontownLittleCat** [comment]
Turns out, I got the same problem. It's normal for developer accounts, but for local, it isn't! I think maybe when local account bridge was migrated to semidbm, it broke the local type. Maybe someone else will fix it.  Sorry I couldn't help you.

**Comment by Teku16** [comment]
@ToontownLittleCat So if I make an account from a different ip, maybe? Also, I got the source I'm using from TTF, wouldnt their server's have a working version of the issue I'm having?

**Comment by enigmeow** [comment]
We are using the mysql driver which is very different.  I will take a look and see what the issue is.

**Comment by Teku16** [comment]
@enigmeow okay thanks :)

**Comment by enigmeow** [comment]
I know I said I would look but I have not had time yet.  By this weekend at worst I will dig into this

**Comment by Teku16** [comment]
Oh, absolutely. Take your time :) I really appreciate you looking into it!

**Comment by enigmeow** [comment]
closed and fixed
